# Generated by Django 5.2.8 on 2025-11-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='প্রশ্ন (e.g., রেজিস্ট্রেশন ফি কত?)', max_length=500)),
                ('answer', models.TextField(help_text='উত্তর - HTML সমর্থিত')),
                ('icon_class', models.CharField(default='help-circle', help_text='Icon class (e.g., fa-dollar-sign, dollar-sign for lucide)', max_length=100)),
                ('style_class', models.CharField(choices=[('faq-item-purple', 'Purple'), ('faq-item-blue', 'Blue'), ('faq-item-green', 'Green'), ('faq-item-orange', 'Orange')], default='faq-item-blue', help_text='FAQ item style class', max_length=50)),
                ('is_important', models.BooleanField(default=False, help_text='গুরুত্বপূর্ণ প্রশ্ন (will be shown first)')),
                ('is_expanded_by_default', models.BooleanField(default=False, help_text='ডিফল্টভাবে খোলা থাকবে')),
                ('order', models.IntegerField(default=0, help_text='ক্রম নম্বর (কম নম্বর আগে দেখাবে)')),
                ('is_active', models.BooleanField(default=True, help_text='সক্রিয় কিনা')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['-is_important', 'order'],
            },
        ),
    ]
