# Generated by Django 5.2.8 on 2025-11-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='শিরোনাম (e.g., অফেরতযোগ্য রেজিস্ট্রেশন)', max_length=200)),
                ('description', models.TextField(help_text='বিস্তারিত বর্ণনা')),
                ('icon_class', models.CharField(default='alert-triangle', help_text='Icon class (e.g., fa-alert-triangle, alert-triangle for lucide)', max_length=100)),
                ('icon_color_class', models.CharField(choices=[('text-error', 'Red (Error)'), ('text-warning', 'Yellow (Warning)'), ('text-info', 'Blue (Info)'), ('text-success', 'Green (Success)'), ('text-accent', 'Purple (Accent)'), ('text-primary', 'Primary Color')], default='text-error', help_text='Icon color class', max_length=50)),
                ('is_critical', models.BooleanField(default=False, help_text='গুরুত্বপূর্ণ শর্ত (will be highlighted)')),
                ('order', models.IntegerField(default=0, help_text='ক্রম নম্বর (কম নম্বর আগে দেখাবে)')),
                ('is_active', models.BooleanField(default=True, help_text='সক্রিয় কিনা')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Terms and Conditions',
                'verbose_name_plural': 'Terms and Conditions',
                'ordering': ['-is_critical', 'order'],
            },
        ),
    ]
