# Generated by Django 5.2.8 on 2025-11-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(help_text='শুরুর সময় (e.g., 09:00)')),
                ('end_time', models.TimeField(help_text='শেষ সময় (e.g., 10:00)')),
                ('title', models.CharField(help_text='শিরোনাম (e.g., রিপোর্টিং ও সকালের নাস্তা)', max_length=200)),
                ('description', models.TextField(help_text='বিস্তারিত বর্ণনা')),
                ('icon_class', models.CharField(default='fa-calendar', help_text='FontAwesome icon class (e.g., fa-coffee, fa-utensils, fa-microphone)', max_length=100)),
                ('color_class', models.CharField(choices=[('icon-wrapper-orange', 'Orange'), ('icon-wrapper-purple', 'Purple'), ('icon-wrapper-green', 'Green'), ('icon-wrapper-blue', 'Blue')], default='icon-wrapper-blue', help_text='Color wrapper class (e.g., icon-wrapper-orange, icon-wrapper-purple)', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='ক্রম নম্বর (কম নম্বর আগে দেখাবে)')),
                ('is_active', models.BooleanField(default=True, help_text='সক্রিয় কিনা')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Schedule Item',
                'verbose_name_plural': 'Schedule Items',
                'ordering': ['order', 'start_time'],
            },
        ),
    ]
