# Generated by Django 5.2.8 on 2025-11-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleitem',
            name='icon_class',
            field=models.CharField(default='calendar', help_text='Lucide icon name (e.g., coffee, utensils, mic, gift, calendar)', max_length=100),
        ),
    ]
