# Generated by Django 5.2.8 on 2025-11-16 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('session', models.CharField(max_length=100, verbose_name='Session')),
                ('contact_number', models.CharField(max_length=20, verbose_name='Contact Number')),
                ('department', models.CharField(max_length=100, verbose_name='Department')),
                ('registration_type', models.CharField(choices=[('Ex Rover', 'Ex Rover'), ('Spouse/Guest', 'Spouse/Guest'), ('Children', 'Children')], max_length=50, verbose_name='Registration Type')),
                ('t_shirt_size', models.CharField(choices=[('XXL', 'XXL'), ('XL', 'XL'), ('L', 'L'), ('M', 'M')], max_length=10, verbose_name='T-Shirt Size')),
                ('last_scouting_stage', models.CharField(choices=[('Rover member', 'Rover member'), ('Rover Mate', 'Rover Mate'), ('Senior Rover Mate', 'Senior Rover Mate')], max_length=50, verbose_name='Last Scouting Stage')),
                ('suggestion', models.TextField(blank=True, null=True, verbose_name='Suggestion For Program If Any')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reunion Registration',
                'verbose_name_plural': 'Reunion Registrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('Bkash', 'Bkash'), ('Nagad', 'Nagad')], max_length=20, verbose_name='Payment Method')),
                ('sender_number', models.CharField(max_length=20, verbose_name='Sender Number')),
                ('trxn_id', models.CharField(max_length=255, unique=True, verbose_name='Transaction ID (Trxn ID)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='registration.registration', verbose_name='Registration')),
            ],
            options={
                'verbose_name': 'Payment Record',
                'verbose_name_plural': 'Payment Records',
            },
        ),
    ]
