# Generated by Django 5.2.8 on 2025-11-16 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ক্যাটাগরির নাম (e.g., সকালের নাস্তা)', max_length=100)),
                ('meal_type', models.CharField(choices=[('breakfast', 'সকালের নাস্তা (Breakfast)'), ('lunch', 'দুপুরের খাবার (Lunch)'), ('snacks', 'বিকালের নাস্তা (Snacks)')], help_text='খাবারের ধরন', max_length=20, unique=True)),
                ('icon_class', models.CharField(default='utensils', help_text='Icon class (e.g., fa-coffee, coffee for lucide)', max_length=100)),
                ('card_color_class', models.CharField(choices=[('food-card-breakfast', 'Breakfast (Pink/Red)'), ('food-card-lunch', 'Lunch (Blue)'), ('food-card-snacks', 'Snacks (Green)')], default='food-card', help_text='Card color class (e.g., food-card-breakfast, food-card-lunch)', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='ক্রম নম্বর')),
                ('is_active', models.BooleanField(default=True, help_text='সক্রিয় কিনা')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meal Category',
                'verbose_name_plural': 'Meal Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='খাবারের নাম (e.g., পরোটা)', max_length=200)),
                ('description', models.CharField(blank=True, help_text='অতিরিক্ত বিবরণ (e.g., গরম গরম, তাজা)', max_length=100)),
                ('quantity', models.CharField(blank=True, help_text='পরিমাণ (e.g., ২টি, ১ বোল)', max_length=50)),
                ('icon_class', models.CharField(default='circle-dot', help_text='Icon class (e.g., circle-dot)', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='ক্রম নম্বর')),
                ('is_active', models.BooleanField(default=True, help_text='সক্রিয় কিনা')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='খাবারের ক্যাটাগরি', on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='food_menu.mealcategory')),
            ],
            options={
                'verbose_name': 'Food Item',
                'verbose_name_plural': 'Food Items',
                'ordering': ['category', 'order'],
            },
        ),
    ]
